console.log("Loading...")
console.log("https://ernestoyoofi.github.io/kelas7bnanggulan To ➡ https://ernestoyoofi.github.io/spesana7b")
console.log("[ !Question ] Website SMPN 1 Nanggulan ? ]")
console.log("[ !Answers ] https://www.smpn1nanggulan.sch.id/")
console.log("This Website Created By Ernesto.yoofi  https://github.com/ernestoyoofi")
console.log("Version 1.5.4 Beta!")
console.log("Tamplate Version : 1.5.4")
console.log("Check Crashed File / Corrupt File In Here [ Consol Log ]")
console.log("Powered High Loading Speed Open GL ES 2.0 By https://ernestoyoofi.github.io/load.js Version 8 JavaVM Mobile")
console.log("Powered Server With https://pages.github.com & file://D:/Server/Local/Storages/SMPN-1-Nanggulan")
console.log("======================================")
console.log("Created By : Ernestoyoofi")
console.log("Starting Upload First : 21:54:09 Waktu Indoneisa Bagian Barat [Yogyakarta] / 14 November 2021")
console.log("Script : [HTML 89%][JS 1%][CSS 10]")
console.log("======================================")